### ISSUE TITLE
Flakey test: `show when format is json`.

### ISSUE THREAD

**Issue by sengi** [alphagov/release#1396]
`show when format is json should return a successful response` flakes.

E.g.

```
Run options: --seed 56721

# Running:

..E

Error:
ApplicationsControllerTest#test_: GET show when format is json should return a successful response. :
RuntimeError: Neutered Exception ActiveRecord::RecordInvalid: Validation failed: Name has already been taken
    test/functional/applications_controller_test.rb:175:in `block (3 levels) in <class:ApplicationsControllerTest>'
    test/functional/applications_controller_test.rb:185:in `block in create_test_from_should_hash'

rails test test/functional/applications_controller_test.rb:178
```

**Comment by sengi** [comment]
Doesn't seem to have flaked in a long time 🤷
